ultravnc: add loadinf functionality
mkevenaar/chocolatey-packages pull request #95
Opened 2021-02-07 18:38 UTC by nwmcsween

## Description
 Adds loadinf functionality to uvnc

## Motivation and Context
Allows precreating inf file for deployments without having to configure (e.g. ldap, etc)

## How Has this Been Tested?
Hasn't, I don't have a env for testing powershell/choco stuff

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Migrated package (a package has been migrated from another repository)

## Checklist:

- [x?] My code follows the code style of this repository.
- [ ] My change requires a change to documentation (this usually means the notes in the description of a package).
- [x] I have updated the documentation accordingly (this usually means the notes in the description of a package).
- [x] All files are up to date with the latest [Contributing Guidelines](https://github.com/mkevenaar/chocolatey-packages/blob/master/CONTRIBUTING.md)
- [ ] The added/modified package passed install/uninstall in the chocolatey test environment.
- [x] The changes only affect a single package (not including meta package).

2021-02-07 18:48 UTC, mkevenaar requested changes
I need a small change before I can merge this. Could you please update this please?

2021-02-07 18:48 UTC, mkevenaar commented on automatic/ultravnc/README.md
> +## Package Specific
A header should be surrounded by new lines, this will be failure on the Chocolatey website..
Could you please update this? Thanks!

2021-02-07 19:39 UTC, mkevenaar requested changes

2021-02-07 19:39 UTC, mkevenaar commented on automatic/ultravnc/README.md
> + * `/LoadInf:` - load an ultravnc inf file
```suggestion
## Package Specific

### Package Parameters

* `/LoadInf:` - load an ultravnc inf file
```

This needs to be changed.

2021-02-07 21:03 UTC, mkevenaar approved these changes
LGTM!

2021-02-07 21:03 UTC, merged

2021-02-07 21:03 UTC, mkevenaar commented
@nwmcsween Your changes have been merged, thank you for your contribution!

2024-11-23 03:24 UTC, Neustradamus commented
Dear all, @mkevenaar,

I have done a ticket to have a fix about bad UltraVNC version numbers in Chocolatey:
- https://github.com/mkevenaar/chocolatey-packages/issues/276

In more, I have done a ticket one year ago about 1.4.3.6:
- https://github.com/mkevenaar/chocolatey-packages/issues/222